# NCTB-SchoolText Audit Report

Aggregates chapter/chunk/flagged-chunk statistics from the Gemma-based OCR audit results,
across all classes and subjects. Subjects are marked **Salvageable** if their flagged-chunk
percentage is at or below the configured threshold, otherwise **Non-salvageable**.

In [1]:
import json
import re
from pathlib import Path
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.width', 160)

## Configuration

`BASE_DIR` is the root folder containing all `classX` folders.
`CLASS_SUBJECTS` maps each class folder name to the list of its subject folders.
`SALVAGEABLE_THRESHOLD` is the max allowed flagged-chunk percentage for a subject
to be considered salvageable.

In [2]:
BASE_DIR = Path(r"D:\Ongoing Research Works\AI-Tutor\NCTB-SchoolText")

SALVAGEABLE_THRESHOLD = 30.0  # percent

CLASS_SUBJECTS = {
    "classOne": [
        "processed_chapters_bangla",
        "processed_chapters_english",
        "processed_chapters_math",
    ],
    "classTwo": [
        "processed_chapters_bangla",
        "processed_chapters_english",
        "processed_chapters_math",
    ],
    "classThree": [
        "processed_chapters_bangla",
        "processed_chapters_bgs",
        "processed_chapters_buddhist_religion",
        "processed_chapters_christian_religion",
        "processed_chapters_english",
        "processed_chapters_hindu_religion",
        "processed_chapters_islam",
        "processed_chapters_math",
        "processed_chapters_science",
    ],
    "classFour": [
        "processed_chapters_bangla",
        "processed_chapters_bgs",
        "processed_chapters_buddhist_religion",
        "processed_chapters_christian_religion",
        "processed_chapters_english",
        "processed_chapters_hindu_religion",
        "processed_chapters_islam",
        "processed_chapters_math",
        "processed_chapters_science",
    ],
    "classFive": [
        "processed_chapters_bangla",
        "processed_chapters_bgs",
        "processed_chapters_buddhist_religion",
        "processed_chapters_christian_religion",
        "processed_chapters_eng",
        "processed_chapters_hindu_religion",
        "processed_chapters_islam",
        "processed_chapters_math",
        "processed_chapters_science",
    ],
    "classSix": [
        "processed_chapters_agriculture",
        "processed_chapters_arabic",
        "processed_chapters_arts_and_crafts",
        "processed_chapters_bangla",
        "processed_chapters_bangla_grammar",
        "processed_chapters_bangla_rapidreader",
        "processed_chapters_bgs",
        "processed_chapters_buddhist_religion",
        "processed_chapters_christian_religion",
        "processed_chapters_english",
        "processed_chapters_english_grammar",
        "processed_chapters_hindu_religion",
        "processed_chapters_home_science",
        "processed_chapters_ict",
        "processed_chapters_islam",
        "processed_chapters_math",
        "processed_chapters_music",
        "processed_chapters_pali",
        "processed_chapters_physical_education",
        "processed_chapters_sanskrit",
        "processed_chapters_science",
        "processed_chapters_work_and_life",
    ],
    "classSeven": [
        "processed_chapters_agriculture",
        "processed_chapters_arabic",
        "processed_chapters_arts_and_crafts",
        "processed_chapters_bangla",
        "processed_chapters_bangla_grammar",
        "processed_chapters_bangla_rapidreader",
        "processed_chapters_bgs",
        "processed_chapters_buddhist_religion",
        "processed_chapters_christian_religion",
        "processed_chapters_english",
        "processed_chapters_english_grammar",
        "processed_chapters_hindu_religion",
        "processed_chapters_home_science",
        "processed_chapters_ict",
        "processed_chapters_islam",
        "processed_chapters_math",
        "processed_chapters_music",
        "processed_chapters_pali",
        "processed_chapters_physical_education",
        "processed_chapters_sanskrit",
        "processed_chapters_science",
        "processed_chapters_work_and_life",
    ],
    "classEight": [
        "processed_chapters_agriculture",
        "processed_chapters_arabic",
        "processed_chapters_arts_and_crafts",
        "processed_chapters_bangla",
        "processed_chapters_bangla_grammar",
        "processed_chapters_bangla_rapidreader",
        "processed_chapters_bgs",
        "processed_chapters_buddhist_religion",
        "processed_chapters_christian_religion",
        "processed_chapters_english",
        "processed_chapters_english_grammar",
        "processed_chapters_hindu_religion",
        "processed_chapters_home_science",
        "processed_chapters_ict",
        "processed_chapters_islam",
        "processed_chapters_math",
        "processed_chapters_music",
        "processed_chapters_pali",
        "processed_chapters_physical_education",
        "processed_chapters_sanskrit",
        "processed_chapters_science",
        "processed_chapters_work_and_life",
    ],
    "classNineTen": [
        "processed_chapters_accounting",
        "processed_chapters_agriculture",
        "processed_chapters_arabic",
        "processed_chapters_arts_and_crafts",
        "processed_chapters_bangla",
        "processed_chapters_bangla_grammar",
        "processed_chapters_bangla_rapidreader",
        "processed_chapters_bgs",
        "processed_chapters_biology_secondary",
        "processed_chapters_buddhist_religion",
        "processed_chapters_business_entrepreneurship",
        "processed_chapters_career_education",
        "processed_chapters_chemistry_secondary",
        "processed_chapters_christian_religion",
        "processed_chapters_civics",
        "processed_chapters_economics",
        "processed_chapters_english",
        "processed_chapters_english_grammar",
        "processed_chapters_finance",
        "processed_chapters_geography",
        "processed_chapters_higher_math",
        "processed_chapters_hindu_religion",
        "processed_chapters_history",
        "processed_chapters_home_science",
        "processed_chapters_ict",
        "processed_chapters_islam",
        "processed_chapters_math",
        "processed_chapters_music",
        "processed_chapters_pali",
        "processed_chapters_physical_education",
        "processed_chapters_physics_secondary",
        "processed_chapters_sanskrit",
        "processed_chapters_science",
    ],
}

## Helper functions

- `chapters_in_config`: total chapters a subject *should* have, read from its
  `chapters_config_<subject>.json` file — this is the ground-truth curriculum total
  and doesn't depend on how much auditing is done yet.
- `chapters_audited` / `chapters_parse_error`: how many chapter audit files in
  `Audit Results` parsed successfully as a list of chunk results vs. failed to parse
  (e.g. saved raw text or an error dict from a failed API call).
- `chunks_total` / `chunks_flagged`: summed only from successfully parsed audit files.

In [3]:
def get_subject_name(subject_folder: str) -> str:
    return subject_folder.replace("processed_chapters_", "", 1)


def get_config_chapter_count(subject_dir: Path, subject_name: str):
    config_path = subject_dir / f"chapters_config_{subject_name}.json"
    if not config_path.exists():
        return None
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return len(data)
    except json.JSONDecodeError:
        pass
    return None


def analyze_subject(class_name: str, subject_folder: str, subject_dir: Path):
    subject_name = get_subject_name(subject_folder)
    chapters_in_config = get_config_chapter_count(subject_dir, subject_name)

    audit_dir = subject_dir / "Audit Results"
    chapters_audited = 0
    chapters_parse_error = 0
    chunks_total = 0
    chunks_flagged = 0

    if audit_dir.exists():
        for audit_file in sorted(audit_dir.glob("*.json")):
            try:
                content = json.loads(audit_file.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                chapters_parse_error += 1
                continue

            if not isinstance(content, list):
                # e.g. an error dict saved from a failed request, or raw non-JSON text
                chapters_parse_error += 1
                continue

            chapters_audited += 1
            chunks_total += len(content)
            chunks_flagged += sum(
                1 for entry in content
                if isinstance(entry, dict) and entry.get("status") == "flagged"
            )

    pct_flagged = round((chunks_flagged / chunks_total * 100), 2) if chunks_total > 0 else None

    if chunks_total == 0:
        salvageable = "N/A (no audited chunks)"
    elif pct_flagged <= SALVAGEABLE_THRESHOLD:
        salvageable = "Salvageable"
    else:
        salvageable = "Non-salvageable"

    return {
        "class": class_name,
        "subject_folder": subject_folder,
        "subject": subject_name,
        "chapters_in_config": chapters_in_config,
        "chapters_audited": chapters_audited,
        "chapters_parse_error": chapters_parse_error,
        "chunks_total": chunks_total,
        "chunks_flagged": chunks_flagged,
        "pct_flagged": pct_flagged,
        "salvageable": salvageable,
    }

## Run the analysis

Walks every class/subject pair defined above and builds one row per subject.

In [4]:
rows = []
for class_name, subject_folders in CLASS_SUBJECTS.items():
    class_dir = BASE_DIR / class_name
    for subject_folder in subject_folders:
        subject_dir = class_dir / subject_folder
        if not subject_dir.exists():
            print(f"! Missing folder, skipping: {subject_dir}")
            continue
        rows.append(analyze_subject(class_name, subject_folder, subject_dir))

subject_df = pd.DataFrame(rows)
subject_df

,class,subject_folder,subject,chapters_in_config,chapters_audited,chapters_parse_error,chunks_total,chunks_flagged,pct_flagged,salvageable
0,classOne,processed_chapters_bangla,bangla,54.0,52,2,56,28,50.00,Non-salvageable
1,classOne,processed_chapters_english,english,5.0,5,0,49,41,83.67,Non-salvageable
2,classOne,processed_chapters_math,math,18.0,18,0,57,53,92.98,Non-salvageable
3,classTwo,processed_chapters_bangla,bangla,30.0,30,0,65,49,75.38,Non-salvageable
4,classTwo,processed_chapters_english,english,10.0,8,2,104,93,89.42,Non-salvageable
5,classTwo,processed_chapters_math,math,7.0,7,0,108,78,72.22,Non-salvageable
6,classThree,processed_chapters_bangla,bangla,30.0,30,0,153,70,45.75,Non-salvageable
7,classThree,processed_chapters_bgs,bgs,13.0,13,0,154,84,54.55,Non-salvageable
8,classThree,processed_chapters_buddhist_religion,buddhist_religion,9.0,9,0,184,90,48.91,Non-salvageable
9,classThree,processed_chapters_christian_religion,christian_religion,5.0,5,0,237,109,45.99,Non-salvageable
10,classThree,processed_chapters_english,english,8.0,8,0,161,89,55.28,Non-salvageable
11,classThree,processed_chapters_hindu_religion,hindu_religion,5.0,5,0,156,54,34.62,Non-salvageable
12,classThree,processed_chapters_islam,islam,5.0,5,0,180,87,48.33,Non-salvageable
13,classThree,processed_chapters_math,math,13.0,12,1,216,163,75.46,Non-salvageable
14,classThree,processed_chapters_science,science,12.0,10,2,188,114,60.64,Non-salvageable
15,classFour,processed_chapters_bangla,bangla,23.0,21,2,205,105,51.22,Non-salvageable
16,classFour,processed_chapters_bgs,bgs,15.0,14,1,187,67,35.83,Non-salvageable
17,classFour,processed_chapters_buddhist_religion,buddhist_religion,5.0,3,2,139,49,35.25,Non-salvageable
18,classFour,processed_chapters_christian_religion,christian_religion,5.0,5,0,288,94,32.64,Non-salvageable
19,classFour,processed_chapters_english,english,18.0,18,0,179,101,56.42,Non-salvageable
20,classFour,processed_chapters_hindu_religion,hindu_religion,5.0,5,0,218,92,42.20,Non-salvageable
21,classFour,processed_chapters_islam,islam,5.0,4,1,172,42,24.42,Salvageable
22,classFour,processed_chapters_math,math,11.0,10,1,262,185,70.61,Non-salvageable
23,classFour,processed_chapters_science,science,12.0,7,5,221,111,50.23,Non-salvageable
24,classFive,processed_chapters_bangla,bangla,23.0,23,0,248,131,52.82,Non-salvageable
25,classFive,processed_chapters_bgs,bgs,17.0,15,2,239,112,46.86,Non-salvageable
26,classFive,processed_chapters_buddhist_religion,buddhist_religion,5.0,5,0,217,77,35.48,Non-salvageable
27,classFive,processed_chapters_christian_religion,christian_religion,5.0,2,3,89,86,96.63,Non-salvageable
28,classFive,processed_chapters_eng,eng,20.0,19,1,223,45,20.18,Salvageable
29,classFive,processed_chapters_hindu_religion,hindu_religion,5.0,5,0,195,97,49.74,Non-salvageable
30,classFive,processed_chapters_islam,islam,5.0,5,0,280,141,50.36,Non-salvageable
31,classFive,processed_chapters_math,math,10.0,10,0,349,221,63.32,Non-salvageable
32,classFive,processed_chapters_science,science,14.0,13,1,450,268,59.56,Non-salvageable
33,classSix,processed_chapters_agriculture,agriculture,6.0,6,0,368,97,26.36,Salvageable
34,classSix,processed_chapters_arabic,arabic,12.0,12,0,60,46,76.67,Non-salvageable
35,classSix,processed_chapters_arts_and_crafts,arts_and_crafts,7.0,7,0,149,41,27.52,Salvageable
36,classSix,processed_chapters_bangla,bangla,20.0,20,0,357,101,28.29,Salvageable
37,classSix,processed_chapters_bangla_grammar,bangla_grammar,14.0,14,0,404,96,23.76,Salvageable
38,classSix,processed_chapters_bangla_rapidreader,bangla_rapidreader,11.0,11,0,237,30,12.66,Salvageable
39,classSix,processed_chapters_bgs,bgs,8.0,8,0,248,69,27.82,Salvageable
40,classSix,processed_chapters_buddhist_religion,buddhist_religion,10.0,10,0,404,100,24.75,Salvageable
41,classSix,processed_chapters_christian_religion,christian_religion,10.0,10,0,431,79,18.33,Salvageable
42,classSix,processed_chapters_english,english,18.0,18,0,333,71,21.32,Salvageable
43,classSix,processed_chapters_english_grammar,english_grammar,10.0,10,0,319,85,26.65,Salvageable
44,classSix,processed_chapters_hindu_religion,hindu_religion,9.0,9,0,343,47,13.70,Salvageable
45,classSix,processed_chapters_home_science,home_science,13.0,13,0,410,116,28.29,Salvageable
46,classSix,processed_chapters_ict,ict,5.0,5,0,255,80,31.37,Non-salvageable
47,classSix,processed_chapters_islam,islam,5.0,4,1,379,73,19.26,Salvageable
48,classSix,processed_chapters_math,math,8.0,7,1,331,150,45.32,Non-salvageable
49,classSix,processed_chapters_music,music,4.0,4,0,218,25,11.47,Salvageable
50,classSix,processed_chapters_pali,pali,11.0,9,2,181,23,12.71,Salvageable
51,classSix,processed_chapters_physical_education,physical_education,5.0,4,1,185,55,29.73,Salvageable
52,classSix,processed_chapters_sanskrit,sanskrit,12.0,11,1,114,61,53.51,Non-salvageable
53,classSix,processed_chapters_science,science,14.0,12,2,481,112,23.28,Salvageable
54,classSix,processed_chapters_work_and_life,work_and_life,3.0,3,0,194,28,14.43,Salvageable
55,classSeven,processed_chapters_agriculture,agriculture,6.0,5,1,408,65,15.93,Salvageable
56,classSeven,processed_chapters_arabic,arabic,7.0,7,0,64,55,85.94,Non-salvageable
57,classSeven,processed_chapters_arts_and_crafts,arts_and_crafts,7.0,7,0,168,51,30.36,Non-salvageable
58,classSeven,processed_chapters_bangla,bangla,26.0,26,0,325,69,21.23,Salvageable
59,classSeven,processed_chapters_bangla_grammar,bangla_grammar,14.0,14,0,485,109,22.47,Salvageable
60,classSeven,processed_chapters_bangla_rapidreader,bangla_rapidreader,14.0,14,0,276,32,11.59,Salvageable
61,classSeven,processed_chapters_bgs,bgs,11.0,11,0,489,94,19.22,Salvageable
62,classSeven,processed_chapters_buddhist_religion,buddhist_religion,10.0,10,0,443,95,21.44,Salvageable
63,classSeven,processed_chapters_christian_religion,christian_religion,10.0,10,0,386,156,40.41,Non-salvageable
64,classSeven,processed_chapters_english,english,9.0,9,0,395,60,15.19,Salvageable
65,classSeven,processed_chapters_english_grammar,english_grammar,19.0,18,1,551,80,14.52,Salvageable
66,classSeven,processed_chapters_hindu_religion,hindu_religion,8.0,8,0,362,93,25.69,Salvageable
67,classSeven,processed_chapters_home_science,home_science,15.0,15,0,601,250,41.60,Non-salvageable
68,classSeven,processed_chapters_ict,ict,5.0,4,1,222,111,50.00,Non-salvageable
69,classSeven,processed_chapters_islam,islam,5.0,4,1,416,116,27.88,Salvageable
70,classSeven,processed_chapters_math,math,11.0,11,0,571,241,42.21,Non-salvageable
71,classSeven,processed_chapters_music,music,3.0,3,0,223,39,17.49,Salvageable
72,classSeven,processed_chapters_pali,pali,7.0,7,0,335,77,22.99,Salvageable
73,classSeven,processed_chapters_physical_education,physical_education,4.0,3,1,155,59,38.06,Non-salvageable
74,classSeven,processed_chapters_sanskrit,sanskrit,9.0,9,0,188,91,48.40,Non-salvageable
75,classSeven,processed_chapters_science,science,14.0,13,1,650,276,42.46,Non-salvageable
76,classSeven,processed_chapters_work_and_life,work_and_life,3.0,3,0,197,29,14.72,Salvageable
77,classEight,processed_chapters_agriculture,agriculture,6.0,6,0,476,53,11.13,Salvageable
78,classEight,processed_chapters_arabic,arabic,12.0,12,0,113,103,91.15,Non-salvageable
79,classEight,processed_chapters_arts_and_crafts,arts_and_crafts,8.0,8,0,158,14,8.86,Salvageable
80,classEight,processed_chapters_bangla,bangla,17.0,0,0,0,0,NaN,N/A (no audited chunks)
81,classEight,processed_chapters_bangla_grammar,bangla_grammar,15.0,15,0,483,195,40.37,Non-salvageable
82,classEight,processed_chapters_bangla_rapidreader,bangla_rapidreader,15.0,15,0,255,40,15.69,Salvageable
83,classEight,processed_chapters_bgs,bgs,13.0,12,1,572,112,19.58,Salvageable
84,classEight,processed_chapters_buddhist_religion,buddhist_religion,11.0,10,1,430,74,17.21,Salvageable
85,classEight,processed_chapters_christian_religion,christian_religion,10.0,10,0,421,43,10.21,Salvageable
86,classEight,processed_chapters_english,english,11.0,10,1,510,101,19.80,Salvageable
87,classEight,processed_chapters_english_grammar,english_grammar,NaN,9,2,393,85,21.63,Salvageable
88,classEight,processed_chapters_hindu_religion,hindu_religion,8.0,6,2,333,39,11.71,Salvageable
89,classEight,processed_chapters_home_science,home_science,14.0,14,0,490,144,29.39,Salvageable
90,classEight,processed_chapters_ict,ict,5.0,4,1,237,98,41.35,Non-salvageable
91,classEight,processed_chapters_islam,islam,5.0,4,1,466,104,22.32,Salvageable
92,classEight,processed_chapters_math,math,11.0,10,1,562,293,52.14,Non-salvageable
93,classEight,processed_chapters_music,music,5.0,4,1,197,18,9.14,Salvageable
94,classEight,processed_chapters_pali,pali,12.0,12,0,573,63,10.99,Salvageable
95,classEight,processed_chapters_physical_education,physical_education,4.0,3,1,134,61,45.52,Non-salvageable
96,classEight,processed_chapters_sanskrit,sanskrit,16.0,16,0,312,110,35.26,Non-salvageable
97,classEight,processed_chapters_science,science,14.0,13,1,635,283,44.57,Non-salvageable
98,classEight,processed_chapters_work_and_life,work_and_life,3.0,3,0,155,32,20.65,Salvageable
99,classNineTen,processed_chapters_accounting,accounting,11.0,10,1,721,172,23.86,Salvageable
100,classNineTen,processed_chapters_agriculture,agriculture,7.0,5,2,354,47,13.28,Salvageable
101,classNineTen,processed_chapters_arabic,arabic,12.0,12,0,425,326,76.71,Non-salvageable
102,classNineTen,processed_chapters_arts_and_crafts,arts_and_crafts,6.0,6,0,416,123,29.57,Salvageable
103,classNineTen,processed_chapters_bangla,bangla,58.0,57,1,989,200,20.22,Salvageable
104,classNineTen,processed_chapters_bangla_grammar,bangla_grammar,49.0,48,1,817,195,23.87,Salvageable
105,classNineTen,processed_chapters_bangla_rapidreader,bangla_rapidreader,5.0,5,0,508,12,2.36,Salvageable
106,classNineTen,processed_chapters_bgs,bgs,14.0,14,0,1216,305,25.08,Salvageable
107,classNineTen,processed_chapters_biology_secondary,biology_secondary,14.0,13,1,923,545,59.05,Non-salvageable
108,classNineTen,processed_chapters_buddhist_religion,buddhist_religion,11.0,10,1,590,83,14.07,Salvageable
109,classNineTen,processed_chapters_business_entrepreneurship,business_entrepreneurship,10.0,10,0,633,205,32.39,Non-salvageable
110,classNineTen,processed_chapters_career_education,career_education,3.0,2,1,157,35,22.29,Salvageable
111,classNineTen,processed_chapters_chemistry_secondary,chemistry_secondary,12.0,10,2,970,514,52.99,Non-salvageable
112,classNineTen,processed_chapters_christian_religion,christian_religion,15.0,14,1,621,93,14.98,Salvageable
113,classNineTen,processed_chapters_civics,civics,10.0,9,1,605,70,11.57,Salvageable
114,classNineTen,processed_chapters_economics,economics,10.0,10,0,693,238,34.34,Non-salvageable
115,classNineTen,processed_chapters_english,english,15.0,15,0,789,106,13.43,Salvageable
116,classNineTen,processed_chapters_english_grammar,english_grammar,21.0,20,1,902,124,13.75,Salvageable
117,classNineTen,processed_chapters_finance,finance,12.0,8,4,333,113,33.93,Non-salvageable
118,classNineTen,processed_chapters_geography,geography,13.0,11,2,697,350,50.22,Non-salvageable
119,classNineTen,processed_chapters_higher_math,higher_math,14.0,12,2,948,669,70.57,Non-salvageable
120,classNineTen,processed_chapters_hindu_religion,hindu_religion,10.0,9,1,533,107,20.08,Salvageable
121,classNineTen,processed_chapters_history,history,11.0,9,2,782,94,12.02,Salvageable
122,classNineTen,processed_chapters_home_science,home_science,13.0,13,0,905,220,24.31,Salvageable
123,classNineTen,processed_chapters_ict,ict,3.0,2,1,393,183,46.56,Non-salvageable
124,classNineTen,processed_chapters_islam,islam,4.0,4,0,791,93,11.76,Salvageable
125,classNineTen,processed_chapters_math,math,17.0,14,3,1009,595,58.97,Non-salvageable
126,classNineTen,processed_chapters_music,music,4.0,4,0,539,133,24.68,Salvageable
127,classNineTen,processed_chapters_pali,pali,11.0,10,1,595,41,6.89,Salvageable
128,classNineTen,processed_chapters_physical_education,physical_education,8.0,7,1,348,107,30.75,Non-salvageable
129,classNineTen,processed_chapters_physics_secondary,physics_secondary,12.0,10,2,908,333,36.67,Non-salvageable
130,classNineTen,processed_chapters_sanskrit,sanskrit,24.0,22,2,484,150,30.99,Non-salvageable
131,classNineTen,processed_chapters_science,science,11.0,9,2,803,258,32.13,Non-salvageable

## 9–12. Per-subject, per-class stats (chapters, chunks, flagged, %, salvageable)

In [5]:
subject_report = subject_df[[
    "class", "subject", "chapters_in_config", "chapters_audited",
    "chunks_total", "chunks_flagged", "pct_flagged", "salvageable"
]].sort_values(["class", "subject"]).reset_index(drop=True)

subject_report

            class                    subject  chapters_in_config  chapters_audited  chunks_total  chunks_flagged  pct_flagged              salvageable
0      classEight                agriculture                 6.0                 6           476              53        11.13              Salvageable
1      classEight                     arabic                12.0                12           113             103        91.15          Non-salvageable
2      classEight            arts_and_crafts                 8.0                 8           158              14         8.86              Salvageable
3      classEight                     bangla                17.0                 0             0               0          NaN  N/A (no audited chunks)
4      classEight             bangla_grammar                15.0                15           483             195        40.37          Non-salvageable
5      classEight         bangla_rapidreader                15.0                15           255              40        15.69              Salvageable
6      classEight                        bgs                13.0                12           572             112        19.58              Salvageable
7      classEight          buddhist_religion                11.0                10           430              74        17.21              Salvageable
8      classEight         christian_religion                10.0                10           421              43        10.21              Salvageable
9      classEight                    english                11.0                10           510             101        19.80              Salvageable
10     classEight            english_grammar                 NaN                 9           393              85        21.63              Salvageable
11     classEight             hindu_religion                 8.0                 6           333              39        11.71              Salvageable
12     classEight               home_science                14.0                14           490             144        29.39              Salvageable
13     classEight                        ict                 5.0                 4           237              98        41.35          Non-salvageable
14     classEight                      islam                 5.0                 4           466             104        22.32              Salvageable
15     classEight                       math                11.0                10           562             293        52.14          Non-salvageable
16     classEight                      music                 5.0                 4           197              18         9.14              Salvageable
17     classEight                       pali                12.0                12           573              63        10.99              Salvageable
18     classEight         physical_education                 4.0                 3           134              61        45.52          Non-salvageable
19     classEight                   sanskrit                16.0                16           312             110        35.26          Non-salvageable
20     classEight                    science                14.0                13           635             283        44.57          Non-salvageable
21     classEight              work_and_life                 3.0                 3           155              32        20.65              Salvageable
22      classFive                     bangla                23.0                23           248             131        52.82          Non-salvageable
23      classFive                        bgs                17.0                15           239             112        46.86          Non-salvageable
24      classFive          buddhist_religion                 5.0                 5           217              77        35.48          Non-salvageable
25      classFive         christian_religion                 5.0                 2            89              86        96.63          Non-salvageable
26      classFive                        eng                20.0                19           223              45        20.18              Salvageable
27      classFive             hindu_religion                 5.0                 5           195              97        49.74          Non-salvageable
28      classFive                      islam                 5.0                 5           280             141        50.36          Non-salvageable
29      classFive                       math                10.0                10           349             221        63.32          Non-salvageable
30      classFive                    science                14.0                13           450             268        59.56          Non-salvageable
31      classFour                     bangla                23.0                21           205             105        51.22          Non-salvageable
32      classFour                        bgs                15.0                14           187              67        35.83          Non-salvageable
33      classFour          buddhist_religion                 5.0                 3           139              49        35.25          Non-salvageable
34      classFour         christian_religion                 5.0                 5           288              94        32.64          Non-salvageable
35      classFour                    english                18.0                18           179             101        56.42          Non-salvageable
36      classFour             hindu_religion                 5.0                 5           218              92        42.20          Non-salvageable
37      classFour                      islam                 5.0                 4           172              42        24.42              Salvageable
38      classFour                       math                11.0                10           262             185        70.61          Non-salvageable
39      classFour                    science                12.0                 7           221             111        50.23          Non-salvageable
40   classNineTen                 accounting                11.0                10           721             172        23.86              Salvageable
41   classNineTen                agriculture                 7.0                 5           354              47        13.28              Salvageable
42   classNineTen                     arabic                12.0                12           425             326        76.71          Non-salvageable
43   classNineTen            arts_and_crafts                 6.0                 6           416             123        29.57              Salvageable
44   classNineTen                     bangla                58.0                57           989             200        20.22              Salvageable
45   classNineTen             bangla_grammar                49.0                48           817             195        23.87              Salvageable
46   classNineTen         bangla_rapidreader                 5.0                 5           508              12         2.36              Salvageable
47   classNineTen                        bgs                14.0                14          1216             305        25.08              Salvageable
48   classNineTen          biology_secondary                14.0                13           923             545        59.05          Non-salvageable
49   classNineTen          buddhist_religion                11.0                10           590              83        14.07              Salvageable
50   classNineTen  business_entrepreneurship                10.0                10           633             205        32.39          Non-salvageable
51   classNineTen           career_education                 3.0                 2           157              35        22.29              Salvageable
52   classNineTen        chemistry_secondary                12.0                10           970             514        52.99          Non-salvageable
53   classNineTen         christian_religion                15.0                14           621              93        14.98              Salvageable
54   classNineTen                     civics                10.0                 9           605              70        11.57              Salvageable
55   classNineTen                  economics                10.0                10           693             238        34.34          Non-salvageable
56   classNineTen                    english                15.0                15           789             106        13.43              Salvageable
57   classNineTen            english_grammar                21.0                20           902             124        13.75              Salvageable
58   classNineTen                    finance                12.0                 8           333             113        33.93          Non-salvageable
59   classNineTen                  geography                13.0                11           697             350        50.22          Non-salvageable
60   classNineTen                higher_math                14.0                12           948             669        70.57          Non-salvageable
61   classNineTen             hindu_religion                10.0                 9           533             107        20.08              Salvageable
62   classNineTen                    history                11.0                 9           782              94        12.02              Salvageable
63   classNineTen               home_science                13.0                13           905             220        24.31              Salvageable
64   classNineTen                        ict                 3.0                 2           393             183        46.56          Non-salvageable
65   classNineTen                      islam                 4.0                 4           791              93        11.76              Salvageable
66   classNineTen                       math                17.0                14          1009             595        58.97          Non-salvageable
67   classNineTen                      music                 4.0                 4           539             133        24.68              Salvageable
68   classNineTen                       pali                11.0                10           595              41         6.89              Salvageable
69   classNineTen         physical_education                 8.0                 7           348             107        30.75          Non-salvageable
70   classNineTen          physics_secondary                12.0                10           908             333        36.67          Non-salvageable
71   classNineTen                   sanskrit                24.0                22           484             150        30.99          Non-salvageable
72   classNineTen                    science                11.0                 9           803             258        32.13          Non-salvageable
73       classOne                     bangla                54.0                52            56              28        50.00          Non-salvageable
74       classOne                    english                 5.0                 5            49              41        83.67          Non-salvageable
75       classOne                       math                18.0                18            57              53        92.98          Non-salvageable
76     classSeven                agriculture                 6.0                 5           408              65        15.93              Salvageable
77     classSeven                     arabic                 7.0                 7            64              55        85.94          Non-salvageable
78     classSeven            arts_and_crafts                 7.0                 7           168              51        30.36          Non-salvageable
79     classSeven                     bangla                26.0                26           325              69        21.23              Salvageable
80     classSeven             bangla_grammar                14.0                14           485             109        22.47              Salvageable
81     classSeven         bangla_rapidreader                14.0                14           276              32        11.59              Salvageable
82     classSeven                        bgs                11.0                11           489              94        19.22              Salvageable
83     classSeven          buddhist_religion                10.0                10           443              95        21.44              Salvageable
84     classSeven         christian_religion                10.0                10           386             156        40.41          Non-salvageable
85     classSeven                    english                 9.0                 9           395              60        15.19              Salvageable
86     classSeven            english_grammar                19.0                18           551              80        14.52              Salvageable
87     classSeven             hindu_religion                 8.0                 8           362              93        25.69              Salvageable
88     classSeven               home_science                15.0                15           601             250        41.60          Non-salvageable
89     classSeven                        ict                 5.0                 4           222             111        50.00          Non-salvageable
90     classSeven                      islam                 5.0                 4           416             116        27.88              Salvageable
91     classSeven                       math                11.0                11           571             241        42.21          Non-salvageable
92     classSeven                      music                 3.0                 3           223              39        17.49              Salvageable
93     classSeven                       pali                 7.0                 7           335              77        22.99              Salvageable
94     classSeven         physical_education                 4.0                 3           155              59        38.06          Non-salvageable
95     classSeven                   sanskrit                 9.0                 9           188              91        48.40          Non-salvageable
96     classSeven                    science                14.0                13           650             276        42.46          Non-salvageable
97     classSeven              work_and_life                 3.0                 3           197              29        14.72              Salvageable
98       classSix                agriculture                 6.0                 6           368              97        26.36              Salvageable
99       classSix                     arabic                12.0                12            60              46        76.67          Non-salvageable
100      classSix            arts_and_crafts                 7.0                 7           149              41        27.52              Salvageable
101      classSix                     bangla                20.0                20           357             101        28.29              Salvageable
102      classSix             bangla_grammar                14.0                14           404              96        23.76              Salvageable
103      classSix         bangla_rapidreader                11.0                11           237              30        12.66              Salvageable
104      classSix                        bgs                 8.0                 8           248              69        27.82              Salvageable
105      classSix          buddhist_religion                10.0                10           404             100        24.75              Salvageable
106      classSix         christian_religion                10.0                10           431              79        18.33              Salvageable
107      classSix                    english                18.0                18           333              71        21.32              Salvageable
108      classSix            english_grammar                10.0                10           319              85        26.65              Salvageable
109      classSix             hindu_religion                 9.0                 9           343              47        13.70              Salvageable
110      classSix               home_science                13.0                13           410             116        28.29              Salvageable
111      classSix                        ict                 5.0                 5           255              80        31.37          Non-salvageable
112      classSix                      islam                 5.0                 4           379              73        19.26              Salvageable
113      classSix                       math                 8.0                 7           331             150        45.32          Non-salvageable
114      classSix                      music                 4.0                 4           218              25        11.47              Salvageable
115      classSix                       pali                11.0                 9           181              23        12.71              Salvageable
116      classSix         physical_education                 5.0                 4           185              55        29.73              Salvageable
117      classSix                   sanskrit                12.0                11           114              61        53.51          Non-salvageable
118      classSix                    science                14.0                12           481             112        23.28              Salvageable
119      classSix              work_and_life                 3.0                 3           194              28        14.43              Salvageable
120    classThree                     bangla                30.0                30           153              70        45.75          Non-salvageable
121    classThree                        bgs                13.0                13           154              84        54.55          Non-salvageable
122    classThree          buddhist_religion                 9.0                 9           184              90        48.91          Non-salvageable
123    classThree         christian_religion                 5.0                 5           237             109        45.99          Non-salvageable
124    classThree                    english                 8.0                 8           161              89        55.28          Non-salvageable
125    classThree             hindu_religion                 5.0                 5           156              54        34.62          Non-salvageable
126    classThree                      islam                 5.0                 5           180              87        48.33          Non-salvageable
127    classThree                       math                13.0                12           216             163        75.46          Non-salvageable
128    classThree                    science                12.0                10           188             114        60.64          Non-salvageable
129      classTwo                     bangla                30.0                30            65              49        75.38          Non-salvageable
130      classTwo                    english                10.0                 8           104              93        89.42          Non-salvageable

## 5–8. Per-class stats (chapters, chunks, flagged, %)

In [6]:
class_df = subject_df.groupby("class", as_index=False).agg(
    chapters_in_config=("chapters_in_config", "sum"),
    chapters_audited=("chapters_audited", "sum"),
    chunks_total=("chunks_total", "sum"),
    chunks_flagged=("chunks_flagged", "sum"),
)

class_df["pct_flagged"] = class_df.apply(
    lambda r: round(r["chunks_flagged"] / r["chunks_total"] * 100, 2) if r["chunks_total"] > 0 else None,
    axis=1,
)

# preserve the class order as defined in CLASS_SUBJECTS rather than alphabetical
class_order = list(CLASS_SUBJECTS.keys())
class_df["class"] = pd.Categorical(class_df["class"], categories=class_order, ordered=True)
class_df = class_df.sort_values("class").reset_index(drop=True)

class_df

          class  chapters_in_config  chapters_audited  chunks_total  chunks_flagged  pct_flagged
0      classOne                77.0                75           162             122        75.31
1      classTwo                47.0                45           277             220        79.42
2    classThree               100.0                97          1629             860        52.79
3     classFour                99.0                87          1871             846        45.22
4     classFive               104.0                97          2290            1178        51.44
5      classSix               215.0               207          6401            1585        24.76
6    classSeven               217.0               211          7910            2248        28.42
7    classEight               215.0               196          7905            2065        26.12
8  classNineTen               450.0               414         22397            6839        30.54

## 1–4. Grand totals across all classes

In [7]:
total_chapters_config = int(subject_df["chapters_in_config"].sum(skipna=True))
total_chapters_audited = int(subject_df["chapters_audited"].sum())
total_chunks = int(subject_df["chunks_total"].sum())
total_flagged = int(subject_df["chunks_flagged"].sum())
overall_pct_flagged = round((total_flagged / total_chunks * 100), 2) if total_chunks > 0 else None

print(f"Total chapters (per chapter configs):      {total_chapters_config}")
print(f"Total chapters actually audited so far:    {total_chapters_audited}")
print(f"Total chunks audited:                      {total_chunks}")
print(f"Total flagged chunks:                      {total_flagged}")
print(f"Overall flagged percentage:                {overall_pct_flagged}%")

Total chapters (per chapter configs):      1524
Total chapters actually audited so far:    1429
Total chunks audited:                      50842
Total flagged chunks:                      15963
Overall flagged percentage:                31.4%

## Save reports to CSV (optional)

In [8]:
subject_report.to_csv(BASE_DIR / "audit_summary_by_subject.csv", index=False)
class_df.to_csv(BASE_DIR / "audit_summary_by_class.csv", index=False)
print("Saved CSV summaries to", BASE_DIR)

Saved CSV summaries to D:\Ongoing Research Works\AI-Tutor\NCTB-SchoolText